### ISSUE TITLE
Can we add some clarification or caveats to the deletion of CVO instance?

### ISSUE THREAD

**Issue by wilshields** [NetAppDocs/occm#542] opened 2021-04-27 21:05 UTC
Page: [Deleting a Cloud Volumes ONTAP working environment](https://docs.netapp.com/us-en/occm/task_deleting_working_env.html)

From a customer perspective, if they are testing CBS, Restores, Compliance, Monitoring, etc..., they tend to lump it all in as CVO and therefore think when deleting CVO that all the other items get cleaned up as well. We know this is not the case.

It would be nice to point this out because the customer will continue to billed for the other resources and in some cases like CBS, they cannot delete them after the CVO instance is deleted and get billed for something they didn't even know they had out there.

**Comment by netapp-bcammett** [comment] 2021-04-28 13:45
Hi Wil,

Thanks for submitting this issue--it's a great suggestion. Here's a draft of the proposed changes for the docs. Please take a look and let me know if anything is missing or unclear.

### Deleting a Cloud Volumes ONTAP working environment

You should always delete Cloud Volumes ONTAP systems from Cloud Manager, rather than from your cloud provider’s console. For example, if you terminate a licensed Cloud Volumes ONTAP instance from your cloud provider, then you can’t use the license key for another instance. You must delete the working environment from Cloud Manager to release the license.

When you delete a working environment, Cloud Manager terminates Cloud Volumes ONTAP instances and deletes disks and snapshots.

Resources managed by other services like backups for Cloud Backup and instances for Cloud Compliance and Monitoring are not deleted when you delete a working environment. You’ll need to manually delete them yourself. If you don’t, then you’ll continue to receive charges for these resources.

NOTE: Cloud Volumes ONTAP instances have termination protection enabled to help prevent accidental termination from AWS. However, if you do terminate a Cloud Volumes ONTAP instance from AWS, you must go to the AWS CloudFormation console and delete the instance’s stack. The stack name is the name of the working environment.

**Steps**

1. If you enabled Cloud Backup on the working environment, [delete all backups of the volumes](https://docs.netapp.com/us-en/occm/task_managing_backups.html#deleting-backups).

Cloud Backup doesn’t automatically delete backups when you delete a system, and there is no current support in the UI to delete the backups after the system has been deleted.

2. If you enabled Cloud Compliance or Monitoring on this working environment and no other working environments use those services, then you’ll need to delete the instances for those services.

- [Learn more about the Cloud Compliance instance](https://docs.netapp.com/us-en/occm/concept_cloud_compliance.html#the-cloud-compliance-instance).

- [Learn more about the Monitoring Acquisition Unit](https://docs.netapp.com/us-en/occm/concept_monitoring.html#the-acquisition-unit).

3. Delete the Cloud Volumes ONTAP working environment.

a. On the Canvas page, double-click the name of the Cloud Volumes ONTAP working environment that you want to delete.

b. Click menu icon and then click Delete.

c. Type the name of the working environment and then click Delete.

It can take up to 5 minutes to delete the working environment.

**Comment by wilshields** [comment] 2021-04-28 14:17
Looks great to me. I have account teams and customers asking me about this a lot so hopefully it clears up some confusion.

v/r  --

Wil Shields
USPS Cloud Solutions Architect (CSA)
7-mode & cDOT Expert (multiple versions) |  Backup & Recovery | AWS CSA
Mobile Phone: 678.379.3664
Schedule a meeting with me<https://app.hubspot.com/meetings/wil-shields>


From: Ben Cammett ***@***.***>
Reply-To: NetAppDocs/occm ***@***.***>
Date: Wednesday, April 28, 2021 at 9:46 AM
To: NetAppDocs/occm ***@***.***>
Cc: "Shields, Wil" ***@***.***>, Author ***@***.***>
Subject: Re: [NetAppDocs/occm] Can we add some clarification or caveats to the deletion of CVO instance? (#542)

NetApp Security WARNING: This is an external email. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Hi Wil,

Thanks for submitting this issue--it's a great suggestion. Here's a draft of the proposed changes for the docs. Please take a look and let me know if anything is missing or unclear.

Deleting a Cloud Volumes ONTAP working environment

You should always delete Cloud Volumes ONTAP systems from Cloud Manager, rather than from your cloud provider’s console. For example, if you terminate a licensed Cloud Volumes ONTAP instance from your cloud provider, then you can’t use the license key for another instance. You must delete the working environment from Cloud Manager to release the license.

When you delete a working environment, Cloud Manager terminates Cloud Volumes ONTAP instances and deletes disks and snapshots.

Resources managed by other services like backups for Cloud Backup and instances for Cloud Compliance and Monitoring are not deleted when you delete a working environment. You’ll need to manually delete them yourself. If you don’t, then you’ll continue to receive charges for these resources.

NOTE: Cloud Volumes ONTAP instances have termination protection enabled to help prevent accidental termination from AWS. However, if you do terminate a Cloud Volumes ONTAP instance from AWS, you must go to the AWS CloudFormation console and delete the instance’s stack. The stack name is the name of the working environment.

Steps

  1.  If you enabled Cloud Backup on the working environment, delete all backups of the volumes<https://docs.netapp.com/us-en/occm/task_managing_backups.html#deleting-backups>.

Cloud Backup doesn’t automatically delete backups when you delete a system, and there is no current support in the UI to delete the backups after the system has been deleted.

  1.  If you enabled Cloud Compliance or Monitoring on this working environment and no other working environments use those services, then you’ll need to delete the instances for those services.

  *   Learn more about the Cloud Compliance instance<https://docs.netapp.com/us-en/occm/concept_cloud_compliance.html#the-cloud-compliance-instance>.
  *   Learn more about the Monitoring Acquisition Unit<https://docs.netapp.com/us-en/occm/concept_monitoring.html#the-acquisition-unit>.

  1.  Delete the Cloud Volumes ONTAP working environment.

a. On the Canvas page, double-click the name of the Cloud Volumes ONTAP working environment that you want to delete.

b. Click menu icon and then click Delete.

c. Type the name of the working environment and then click Delete.

It can take up to 5 minutes to delete the working environment.

**Comment by nichollri** [comment] 2021-04-28 14:39
I would indicate somewhere in here that Cloud Backup is independent from
Cloud Volumes ONTAP by design and that before deleting any entities related
to Cloud Backup it should be determined that the backed up data is no
longer required.

**Comment by netapp-bcammett** [comment] 2021-04-28 14:58
Hi Richard,

How about changing step 1 from this:

> 1. If you enabled Cloud Backup on the working environment, delete all backups of the volumes.
> 
> Cloud Backup doesn’t automatically delete backups when you delete a system, and there is no current support in the UI to delete the backups after the system has been deleted.

To this:

> 1. If you enabled Cloud Backup on the working environment, determine whether the backed up data is still required and then delete the backups, if necessary.
> 
> Cloud Backup is independent from Cloud Volumes ONTAP by design. Cloud Backup doesn’t automatically delete backups when you delete a Cloud Volumes ONTAP system, and there is no current support in the UI to delete the backups after the system has been deleted.

**Comment by nichollri** [comment] 2021-04-28 19:24
Perfect!

**Comment by netapp-bcammett** [comment] 2021-04-28 19:35
Thanks, guys. I have this ready to go for a doc update that should go out on Sunday. I'll close this issue when that's done.

**Comment by netapp-bcammett** [comment] 2021-05-05 20:30
The doc update was published:
https://docs.netapp.com/us-en/occm/task_deleting_working_env.html

Thanks again for the feedback!

**Closed by netapp-bcammett** 2021-05-05 20:30 UTC
